#!/bin/bash
cd /opt
apt update
#java installation
wget -c --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.rpm
#start the java
rpm -ivh jdk-8u131-linux-x64.rpm
#install jenkins in linux os
wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
yum -y install jenkins -y
systemctl start jenkins
systemctl enable jenkins



su - jenkins -s bin/bash
cd /etc
vi passwd
last line bin/bash cahnge line
inside jenkins dont ask sudo passwd give command
visudo
#set number
:set nu
100 line chanege
root    ALL=(ALL)       ALL
jenkins    ALL=(ALL)       ALL
vi sudoers.d/90-cloud-init-users
#cahnge ec2-user to jenkins
