#!/bin/bash
cd /opt
#install java
wget wget -c --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.rpm
rpm -ivh jdk-8u131-linux-x64.rpm
#install tomcat
https://mirrors.estointernet.in/apache/tomcat/tomcat-9/v9.0.48/bin/apache-tomcat-9.0.48-windows-x64.zip
unzip apache-tomcat-9.0.48-windows-x64.zip
mv apache-tomcat-9.0.48 tomcat
chmod -R 700 tomcat 
cd tomcat/bin/
./startup.sh 
cd ../../
wget https://www.oracle.com/webfolder/technetwork/tutorials/obe/fmw/wls/10g/r3/cluster/session_state/files/shoppingcart.zip
unzip shoppingcart.zip
rm -f shoppingcart.zip
cp shoppingcart.war /opt/tomcat/webapps/
